import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { Type } from "class-transformer";
import {
	IsBooleanString,
	IsDateString,
	IsEnum,
	IsInt,
	IsNotEmpty,
	IsNumber,
	IsOptional,
	IsString,
	Max,
	MaxLength,
	Min,
} from "class-validator";
import { PERIODS } from "../../common/utils/period.util";

/** Every transaction type, including system-generated ones (used for reads and filters). */
enum TransactionType {
	INCOME = "INCOME",
	EXPENSE = "EXPENSE",
	TRANSFER = "TRANSFER",
	PAYMENT = "PAYMENT",
	INSTALLMENT = "INSTALLMENT",
}

/**
 * Types a user can create or switch to. INSTALLMENT is system-only: those rows are
 * generated by the statement engine at each cut.
 */
enum UserTransactionType {
	INCOME = "INCOME",
	EXPENSE = "EXPENSE",
	TRANSFER = "TRANSFER",
	PAYMENT = "PAYMENT",
}

enum TransactionSortBy {
	date = "date",
	amount = "amount",
	createdAt = "createdAt",
}

enum SortOrder {
	asc = "asc",
	desc = "desc",
}

enum InstallmentPlanType {
	MSI = "MSI",
	MSCI = "MSCI",
}

enum CommissionType {
	ANNUAL_FEE = "ANNUAL_FEE",
	LATE_PAYMENT = "LATE_PAYMENT",
	CASH_ADVANCE = "CASH_ADVANCE",
}

export class CreateTransactionDto {
	@ApiProperty({ example: "account-uuid", description: "Source account ID (where money leaves)" })
	@IsString()
	@IsNotEmpty()
	accountId!: string;

	@ApiPropertyOptional({
		example: "destination-uuid",
		description:
			"Destination account ID (required for TRANSFER and PAYMENT, null for INCOME/EXPENSE)",
	})
	@IsOptional()
	@IsString()
	destinationAccountId?: string | null;

	@ApiPropertyOptional({
		example: "category-uuid",
		description: "Category ID (optional, for INCOME/EXPENSE categorization)",
	})
	@IsOptional()
	@IsString()
	categoryId?: string;

	@ApiProperty({
		enum: UserTransactionType,
		example: "EXPENSE",
		description: "Transaction type (INSTALLMENT is system-only and rejected)",
	})
	@IsEnum(UserTransactionType)
	type!: UserTransactionType;

	@ApiProperty({ example: 1500.0, description: "Transaction amount" })
	@Type(() => Number)
	@IsNumber()
	@Min(0)
	amount!: number;

	@ApiPropertyOptional({ example: "Grocery shopping", description: "Short description" })
	@IsOptional()
	@IsString()
	@MaxLength(200)
	description?: string;

	@ApiPropertyOptional({ example: "Weekly groceries at Walmart", description: "Detailed note" })
	@IsOptional()
	@IsString()
	@MaxLength(1000)
	note?: string;

	@ApiPropertyOptional({
		example: "2026-07-28T12:00:00.000Z",
		description: "Transaction date (defaults to now)",
	})
	@IsOptional()
	@IsDateString()
	date?: string;

	@ApiPropertyOptional({
		example: 12,
		description: "Number of months for MSI/MSCI installment plan (1-36)",
	})
	@IsOptional()
	@Type(() => Number)
	@IsInt()
	@Min(1)
	@Max(36)
	msiMonths?: number;

	@ApiPropertyOptional({
		enum: InstallmentPlanType,
		example: "MSI",
		description: "Installment plan type (MSI = sin intereses, MSCI = con intereses)",
	})
	@IsOptional()
	@IsEnum(InstallmentPlanType)
	msiType?: InstallmentPlanType;

	@ApiPropertyOptional({
		example: 0.12,
		description: "Promotional interest rate for MSCI plans (e.g. 0.12 = 12%)",
	})
	@IsOptional()
	@Type(() => Number)
	@IsNumber()
	msiRate?: number;

	@ApiPropertyOptional({
		enum: CommissionType,
		example: "ANNUAL_FEE",
		description:
			"Commission type for typed EXPENSE transactions (ANNUAL_FEE, LATE_PAYMENT, CASH_ADVANCE)",
	})
	@IsOptional()
	@IsEnum(CommissionType)
	commissionType?: CommissionType;
}

export class UpdateTransactionDto {
	@ApiPropertyOptional({ example: "account-uuid", description: "Source account ID" })
	@IsOptional()
	@IsString()
	@IsNotEmpty()
	accountId?: string;

	@ApiPropertyOptional({ example: "destination-uuid", description: "Destination account ID" })
	@IsOptional()
	@IsString()
	destinationAccountId?: string | null;

	@ApiPropertyOptional({ example: "category-uuid", description: "Category ID" })
	@IsOptional()
	@IsString()
	categoryId?: string | null;

	@ApiPropertyOptional({
		enum: UserTransactionType,
		example: "EXPENSE",
		description: "Transaction type (INSTALLMENT is system-only and rejected)",
	})
	@IsOptional()
	@IsEnum(UserTransactionType)
	type?: UserTransactionType;

	@ApiPropertyOptional({ example: 1500.0, description: "Transaction amount" })
	@IsOptional()
	@Type(() => Number)
	@IsNumber()
	@Min(0)
	amount?: number;

	@ApiPropertyOptional({ example: "Grocery shopping", description: "Short description" })
	@IsOptional()
	@IsString()
	@MaxLength(200)
	description?: string;

	@ApiPropertyOptional({ example: "Weekly groceries at Walmart", description: "Detailed note" })
	@IsOptional()
	@IsString()
	@MaxLength(1000)
	note?: string;

	@ApiPropertyOptional({ example: "2026-07-28T12:00:00.000Z", description: "Transaction date" })
	@IsOptional()
	@IsDateString()
	date?: string;
}

export class TransactionResponseDto {
	@ApiProperty({ example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890", description: "Transaction ID" })
	id!: string;

	@ApiProperty({ example: "account-uuid", description: "Source account ID" })
	accountId!: string;

	@ApiPropertyOptional({
		example: "destination-uuid",
		description: "Destination account ID (TRANSFER/PAYMENT only)",
	})
	destinationAccountId!: string | null;

	@ApiPropertyOptional({ example: "category-uuid", description: "Category ID" })
	categoryId!: string | null;

	@ApiProperty({ enum: TransactionType, example: "EXPENSE", description: "Transaction type" })
	type!: TransactionType;

	@ApiProperty({ example: 1500.0, description: "Transaction amount" })
	amount!: number;

	@ApiPropertyOptional({ example: "Grocery shopping", description: "Short description" })
	description!: string | null;

	@ApiPropertyOptional({ example: "Weekly groceries at Walmart", description: "Detailed note" })
	note!: string | null;

	@ApiProperty({ example: "2026-07-28T12:00:00.000Z", description: "Transaction date" })
	date!: Date;

	@ApiProperty({ example: "2026-07-28T12:00:00.000Z", description: "Creation date" })
	createdAt!: Date;

	@ApiProperty({ example: "2026-07-28T12:00:00.000Z", description: "Last update date" })
	updatedAt!: Date;

	@ApiPropertyOptional({
		example: "stmt-uuid",
		description: "Linked card statement ID (set by statement generation, read-only)",
	})
	statementId?: string | null;

	@ApiPropertyOptional({
		enum: CommissionType,
		example: "ANNUAL_FEE",
		description: "Commission type (null for regular transactions)",
	})
	commissionType?: CommissionType | null;
}

export class TransactionsInfoDto {
	@ApiProperty({ example: 12500000, description: "Net worth (assets - liabilities)" })
	netWorth!: number;

	@ApiProperty({ example: 8000000, description: "Liquidity (DEBIT + CASH balances)" })
	liquidity!: number;

	@ApiProperty({ example: 5500000, description: "Debt (CREDIT + LOAN balances, positive value)" })
	debt!: number;
}

export class QueryTransactionsDto {
	@ApiPropertyOptional({
		example: "account-uuid",
		description: "Filter by account (source or destination)",
	})
	@IsOptional()
	@IsString()
	accountId?: string;

	@ApiPropertyOptional({
		enum: TransactionType,
		example: "EXPENSE",
		description: "Filter by transaction type",
	})
	@IsOptional()
	@IsEnum(TransactionType)
	type?: TransactionType;

	@ApiPropertyOptional({ example: "category-uuid", description: "Filter by category" })
	@IsOptional()
	@IsString()
	categoryId?: string;

	@ApiPropertyOptional({
		example: "bank-uuid",
		description: "Filter by accounts belonging to this bank",
	})
	@IsOptional()
	@IsString()
	bankId?: string;

	@ApiPropertyOptional({
		example: "grocery",
		description: "Partial case-insensitive search in description",
	})
	@IsOptional()
	@IsString()
	search?: string;

	@ApiPropertyOptional({
		example: "2026-07-01T00:00:00.000Z",
		description: "Start date (ISO 8601)",
	})
	@IsOptional()
	@IsDateString()
	from?: string;

	@ApiPropertyOptional({ example: "2026-07-31T23:59:59.999Z", description: "End date (ISO 8601)" })
	@IsOptional()
	@IsDateString()
	to?: string;

	@ApiPropertyOptional({ example: 1, description: "Page number (default 1)" })
	@IsOptional()
	@Type(() => Number)
	@IsInt()
	@Min(1)
	page?: number;

	@ApiPropertyOptional({ example: 50, description: "Items per page (default 50, max 100)" })
	@IsOptional()
	@Type(() => Number)
	@IsInt()
	@Min(1)
	limit?: number;

	@ApiPropertyOptional({
		enum: TransactionSortBy,
		example: "date",
		default: "date",
		description: "Sort field",
	})
	@IsOptional()
	@IsEnum(TransactionSortBy)
	sortBy?: TransactionSortBy;

	@ApiPropertyOptional({
		enum: SortOrder,
		example: "desc",
		default: "desc",
		description: "Sort order",
	})
	@IsOptional()
	@IsEnum(SortOrder)
	order?: SortOrder;

	@ApiPropertyOptional({
		example: "true",
		default: "false",
		description:
			'Include financial info summary (netWorth, liquidity, debt) in the response (accepts "true"/"false")',
	})
	@IsOptional()
	@IsBooleanString()
	info?: string;

	@ApiPropertyOptional({
		enum: PERIODS,
		default: "month",
		description:
			"Filter transactions by period. When set, overrides from/to with the computed date range. Defaults to all transactions if omitted.",
	})
	@IsOptional()
	@IsString()
	period?: string;
}
